name: Ultralytics Actions
on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Run Ultralytics Formatting
        uses: ultralytics/actions@main
        with:
          labels: true
          links: false
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          prettier: true
          python: true
          spelling: true
          summary: true
          token: ${{ secrets._GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740376413.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740376413.json
