name: Check Broken links
on:
  push:
    branches:
      - main

jobs:
  Links:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Download and install lychee
        run: 'LYCHEE_URL=$(curl -s https://api.github.com/repos/lycheeverse/lychee/releases/latest
          | grep "browser_download_url" | grep "x86_64-unknown-linux-gnu.tar.gz" |
          cut -d ''"'' -f 4)

          curl -L $LYCHEE_URL | tar xz -C /usr/local/bin

          '
      - id: measurement-3
        name: Record Measurement After Download and install lychee
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Download and install lychee
          task: get-measurement
      - name: Test Markdown and HTML links with retry
        uses: ultralytics/actions/retry@main
        with:
          retries: 2
          retry_delay_seconds: 60
          run: 'lychee \

            --scheme ''https'' \

            --timeout 60 \

            --insecure \

            --accept 403,429,500,502,999 \

            --exclude-all-private \

            --exclude ''https?://(www\.)?(linkedin\.com|twitter\.com|instagram\.com|kaggle\.com|fonts\.gstatic\.com|url\.com)''
            \

            --exclude-path ''**/ci.yaml'' \

            --github-token ${{ secrets.GITHUB_TOKEN }} \

            --header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
            (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36" \

            ''./**/*.md'' \

            ''./**/*.html'' | tee -a $GITHUB_STEP_SUMMARY

            '
          timeout_minutes: 5
      - if: github.event_name == 'workflow_dispatch'
        name: Test Markdown, HTML, YAML, Python and Notebook links with retry
        uses: ultralytics/actions/retry@main
        with:
          retries: 2
          retry_delay_seconds: 60
          run: 'lychee \

            --scheme ''https'' \

            --timeout 60 \

            --insecure \

            --accept 429,999 \

            --exclude-all-private \

            --exclude ''https?://(www\.)?(linkedin\.com|twitter\.com|instagram\.com|kaggle\.com|fonts\.gstatic\.com|url\.com)''
            \

            --exclude-path ''**/ci.yaml'' \

            --github-token ${{ secrets.GITHUB_TOKEN }} \

            --header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
            (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36" \

            ''./**/*.md'' \

            ''./**/*.html'' \

            ''./**/*.yml'' \

            ''./**/*.yaml'' \

            ''./**/*.py'' \

            ''./**/*.ipynb'' | tee -a $GITHUB_STEP_SUMMARY

            '
          timeout_minutes: 5
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740376413.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740376413.json
